const foodItem = [
  {
    id: 1,
    name: "Ambur Biryani",
    category: "biryani",
    rating: 4.3,
    price: 130,
    quantity: 1,
  },
  {
    id: 2,
    name: "Hyderabadi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 3,
    name: "Egg Biryani",
    category: "biryani",
    rating: 4.3,
    price: 180,
    quantity: 1,
  },
  {
    id: 4,
    name: "Goan Fish Biryani",
    category: "biryani",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 5,
    name: "Mutton Biryani",
    category: "biryani",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 6,
    name: "Kamrupi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 120,
    quantity: 1,
  },
  {
    id: 7,
    name: "Kashmiri Biryani",
    category: "biryani",
    rating: 4.3,
    price: 130,
    quantity: 1,
  },
  {
    id: 8,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 200,
    quantity: 1,
  },
  {
    id: 9,
    name: "Mughlai Biryani",
    category: "biryani",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 10,
    name: "Chicken Roast",
    category: "chicken",
    rating: 4.3,
    price: 110,
    quantity: 1,
  },
  {
    id: 11,
    name: "Chicken Curry",
    category: "chicken",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 12,
    name: "Chicken Do Pyaza",
    category: "chicken",
    rating: 4.3,
    price: 140,
    quantity: 1,
  },
  {
    id: 13,
    name: "Chicken Masala",
    category: "chicken",
    rating: 4.3,
    price: 120,
    quantity: 1,
  },
  {
    id: 14,
    name: "Handi Chicken",
    category: "chicken",
    rating: 4.3,
    price: 170,
    quantity: 1,
  },
  {
    id: 15,
    name: "Murgh Musallam",
    category: "chicken",
    rating: 4.3,
    price: 200,
    quantity: 1,
  },
  {
    id: 16,
    name: "Matar Paneer",
    category: "paneer",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 17,
    name: "Palak Paneer",
    category: "paneer",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 18,
    name: "Paneer Butter Masala",
    category: "paneer",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 19,
    name: "Paneer Do Pyaza",
    category: "paneer",
    rating: 4.3,
    price: 120,
    quantity: 1,
  },
  {
    id: 20,
    name: "Hyderabadi Paneer",
    category: "paneer",
    rating: 4.3,
    price: 80,
    quantity: 1,
  },
  {
    id: 21,
    name: "Paneer Lababdar",
    category: "paneer",
    rating: 4.3,
    price: 70,
    quantity: 1,
  },
  {
    id: 22,
    name: "Shahi Paneer",
    age: "32",
    category: "paneer",
    rating: 4.3,
    price: 50,
    quantity: 1,
  },
  {
    id: 23,
    name: "Navratan Korma",
    category: "vegetable",
    rating: 4.3,
    price: 80,
    quantity: 1,
  },
  {
    id: 24,
    name: "Veg Jalfrezi",
    category: "vegetable",
    rating: 4.3,
    price: 70,
    quantity: 1,
  },
  {
    id: 25,
    name: "Veg Biryani",
    category: "vegetable",
    rating: 4.3,
    price: 50,
    quantity: 1,
  },
  {
    id: 26,
    name: "Veg Curry",
    category: "vegetable",
    rating: 4.3,
    price: 70,
    quantity: 1,
  },
  {
    id: 27,
    name: "Veg Kolhapur",
    category: "vegetable",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 28,
    name: "Veg Masala",
    category: "vegetable",
    rating: 4.3,
    price: 90,
    quantity: 1,
  },
  {
    id: 29,
    name: "Veg Pakora",
    category: "vegetable",
    rating: 4.3,
    price: 80,
    quantity: 1,
  },
  {
    id: 30,
    name: "Momos",
    category: "chinese",
    rating: 4.3,
    price: 89,
    quantity: 1,
  },
  {
    id: 31,
    name: "Chicken Manchurian",
    category: "chinese",
    rating: 4.3,
    price: 79,
    quantity: 1,
  },
  {
    id: 32,
    name: "Chili Chicken",
    category: "chinese",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 33,
    name: "Chowmein",
    category: "chinese",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 34,
    name: "Spring Roll",
    category: "chinese",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 35,
    name: "Szechuan Chicken",
    category: "chinese",
    rating: 4.3,
    price: 110,
    quantity: 1,
  },
  {
    id: 36,
    name: "Fried Rice",
    category: "chinese",
    rating: 4.3,
    price: 89,
    quantity: 1,
  },
  {
    id: 37,
    name: "Butter Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 108,
    quantity: 1,
  },
  {
    id: 38,
    name: "Idli",
    category: "south indian",
    rating: 4.3,
    price: 50,
    quantity: 1,
  },
  {
    id: 39,
    name: "Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 120,
    quantity: 1,
  },
  {
    id: 40,
    name: "Mysore Bonda",
    category: "south indian",
    rating: 4.3,
    price: 150,
    quantity: 1,
  },
  {
    id: 41,
    name: "Onion Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 100,
    quantity: 1,
  },
  {
    id: 42,
    name: "Plain Dosa",
    category: "south indian",
    rating: 4.3,
    price: 80,
    quantity: 1,
  },
  {
    id: 43,
    name: "Rava Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 95,
    quantity: 1,
  },
  {
    id: 44,
    name: "Sambhar Vada",
    category: "south indian",
    rating: 4.3,
    price: 84,
    quantity: 1,
  },
];

export { foodItem };
